const colors = {
    white: '#ffffff',
    black: '#000000',
    grey_0: '#d5d5d5',
    grey_1: '#a6a6a6',
    red: '#e84118',
    blue: '#3679fe',
};

export const theme = {
    colors: {
        white: colors.white,
        black: colors.black,
        grey_0: colors.grey_0,
        grey_1: colors.grey_1,
        red: colors.red,
        blue: colors.blue,
    },
    fonts: {
        regular: 'SUIT-Regular',
        bold: 'SUIT-Bold',
        medium: 'SUIT-Medium',
        extrabold:'SUIT-ExtraBold',
    },
    background: colors.white,
    text: colors.black,
    errorText: colors.red,
    imageBackground: colors.grey_0,
    imageButtonBackgroud: colors.grey_1,
    imageButtonIcon: colors.white,
    label: colors.grey_1,
    inputPlaceholder: colors.grey_1,
    inputBorder: colors.grey_1,
    inputDisabledBackground: colors.grey_0,
    buttonBackground: "#1D1D1F",
    buttonTitle: colors.white,
    buttonUnfilledTitle: colors.blue,
    buttonLogout: colors.red,
    headerTintColor: colors.black,
    tabActiveColor: colors.blue,
    tabInactiveColor: colors.grey_1,
    spinnerBackground: colors.black,
    spinnerIndicator: colors.white,
    listBorder: colors.grey_0,
    listTime: colors.grey_1,
    listDescription: colors.grey_1,
    listIcon: colors.black,
    sendButtonActive: colors.blue,
    sendButtonInActive: colors.grey_1,
};
